### ISSUE TITLE
Not working for my stop

### ISSUE THREAD

**Issue by aLECChe** [winstonma/MMM-HK-KMB#3]
Hi Wiston,

The module is working fine with the default bus stop.

![test-001](https://user-images.githubusercontent.com/64255284/81492672-511c1500-92cc-11ea-9f10-2d021273a50e.jpg)

But it seems it does not work for my bus stop: KW16-W-2200-0

![test-003](https://user-images.githubusercontent.com/64255284/81492704-ad7f3480-92cc-11ea-95b1-0f16bbf33120.jpg)

![test-002](https://user-images.githubusercontent.com/64255284/81492677-56795f80-92cc-11ea-9eed-0ee93e94f2e1.jpg)

Thank you very much for this update!
aLEC

**Comment by winstonma** [comment]
9acc230

**Comment by aLECChe** [comment]
It is working fine now. It's wonderful!

![20200511](https://user-images.githubusercontent.com/64255284/81517871-cc360780-936e-11ea-8422-59bc527008c6.jpg)

**Comment by winstonma** [comment]
I would like to use `KW16-W-2200-0` as an example. Since one stop could have multiple BSI-Code (站柱) (please take a look at [Fandom page](https://hkbus.fandom.com/wiki/%E5%BE%B7%E7%A6%8F%E8%8A%B1%E5%9C%92_(%E8%A7%80%E5%A1%98%E9%81%93))). So I initially have no idea how to get the correct stop name. Hope this way fixes the problem.

Currently the bus lines are sorted by BSI-Code, which is the geographic location of the stop.

**Comment by winstonma** [comment]
Hi @aLECChe may I ask you something. I'd like to know how you start the MagicMirror module? `npm start` or `npm run server`?

Based on the code, I guess `npm start` may have a timing issue.

**Comment by aLECChe** [comment]
I follow the below instructions to autostart my MagicMirror, which I think is basically npm start.
https://github.com/MichMich/MagicMirror/wiki/Auto-Starting-MagicMirror

**Comment by winstonma** [comment]
Great

Then I would leave the current code as it is.
