### ISSUE TITLE
ETA is off by several hours

### ISSUE THREAD

**Issue by winstonma** [winstonma/MMM-HK-KMB#8]
In some device, the ETA would be off. Please see the screenshot below:

![Image1](https://user-images.githubusercontent.com/1215090/91651314-e2063e80-eabd-11ea-9c6d-c1f2b4e7d470.jpg)

**Comment by winstonma** [comment]
@faiyip, would you mind joining [MMM-HK-KMB](https://join.slack.com/t/mmm-hk-kmb/shared_invite/zt-h5kwh6qp-DFv6oUsilbhXnYSLXfoM1w) slack channel?

I would need more info. Thanks

**Comment by faiyip** [comment]
hi,
  ETA is still off by 4 hours.
  Language works if my setting is "zh-tw", however, since this module is
for Hong Kong Kowloon bus, shouldn't zh-hk be the default? I tried to copy
the translation , and added an entry for zh-hk, but no use.

Thanks
Fai

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
@faiyip The reason why I didn't use `zh-hk` is because I checked the translation page of MagicMirror ([Link](https://github.com/MichMich/MagicMirror/tree/master/translations)) and saw `zh-tw.json` and `zh-cn.json`. Will do that later.

For the off time issue, would you mind joining the [MMM-HK-KMB](https://join.slack.com/t/mmm-hk-kmb/shared_invite/zt-h5kwh6qp-DFv6oUsilbhXnYSLXfoM1w) slack channel?

Thanks

**Comment by winstonma** [comment]
@faiyip https://github.com/winstonma/MMM-HK-KMB/commit/d7bd9d362efeebe420bf6409a10d831e5f8a1f71 should fixes the problem.

**Comment by faiyip** [comment]
schedule is now corrected.
I added the following line to fix my language problem, Common.js line 66
        if (config.language === 'zh-hk') return 'zh-hant';

Thanks
Fai

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by winstonma** [comment]
@faiyip Thanks again for your time.

Yeah I would like to support `zh-hk`. But please give me this weekend to see if there are some better way. Stay tunes.

And also Thanks again for your patience in MMM-HK-KMB.
